The Activity Lifecycle
amitshekhariitbhu/android-interview-questions pull request #118
Opened 2022-04-29 08:18 UTC by samvgorode

The Activity Lifecycle - described main callbacks in short, Added the link to official https://developer.android.com/ site.

2022-07-23 16:28 UTC, sud007 approved these changes
looks better

2023-11-08 00:35 UTC, archow commented on README.md
> +     - onRestart() - Called after onStop() when the current activity is being re-displayed to the user (the user has navigated back to it). It will be followed by onStart() and then onResume().
This is great! Very easy to understand, and I appreciate that you added the source link for more information and cross checking. 
The youtube link does not seem to work anymore however.

Is there a way we can add more admins to this project to help approve changes? Preferably after two or more approvals from Android devs or source-checking.

2023-11-08 00:35 UTC, archow approved these changes

2023-11-08 00:36 UTC, archow requested changes
Fix merge conflicts

2024-01-28 16:01 UTC, closed without merging